export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css'

// Configure rendering at the root to avoid SSG errors
export const dynamic = 'force-dynamic';
export const revalidate = false;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 antialiased">{children}</body>
    </html>
  )
}
